/*
	Eingebettete ("frozen") Default-Configs. Fehlt config_wii.json bzw.
	config_pc.json zur Laufzeit, wird der hier eingebettete Inhalt an den
	erwarteten Pfad geschrieben und geladen -- so startet das Spiel auf beiden
	Plattformen auch ohne mitgelieferte Config.

	Inhalt 1:1 aus config_wii.json / config_pc.json. Bei Aenderungen an den
	Config-Dateien diesen Header neu generieren (siehe config_frozen-Skript).
*/

#ifndef CONFIG_FROZEN_H
#define CONFIG_FROZEN_H

#ifdef PLATFORM_WII
static const char* FROZEN_CONFIG_WII =
	"{\n"
	"\t\"paths\": {\n"
	"\t\t\"texturepack\": \"assets\",\n"
	"\t\t\"worlds\": \"saves\",\n"
	"\t\t\"MP3\": \"assets/sound\",\n"
	"\t\t\"sounds\": \"assets/sound/sound\",\n"
	"\t\t\"tmp\": \"tmp\",\n"
	"\t\t\"python_file\": \"init.py\"\n"
	"\t},\n"
	"\t\"input\": {\n"
	"\t\t\"player_forward\": [0, 200, 910],\n"
	"\t\t\"player_backward\": [1, 201, 911],\n"
	"\t\t\"player_left\": [2, 202, 912],\n"
	"\t\t\"player_right\": [3, 203, 913],\n"
	"\t\t\"player_jump\": [5, 210],\n"
	"\t\t\"player_sneak\": [211],\n"
	"\t\t\"item_action_left\": [100, 204],\n"
	"\t\t\"item_action_right\": [101, 205],\n"
	"\t\t\"scroll_left\": [9, 208, 213],\n"
	"\t\t\"scroll_right\": [8, 209, 212],\n"
	"\t\t\"inventory\": [6, 206],\n"
	"\t\t\"open_menu\": [10, 214],\n"
	"\t\t\"gui_up\": [0, 200, 900, 910, 920],\n"
	"\t\t\"gui_down\": [1, 201, 901, 911, 921],\n"
	"\t\t\"gui_left\": [2, 202, 902, 912, 922],\n"
	"\t\t\"gui_right\": [3, 203, 903, 913, 923],\n"
	"\t\t\"gui_click\": [4, 204],\n"
	"\t\t\"gui_click_alt\": [5, 205],\n"
	"\t\t\"screenshot\": [7],\n"
	"\t\t\"gui_back\": [5, 210],\n"
	"\t\t\"any_button\": [0, 1, 2, 3, 4, 5, 6, 7,\n"
	"\t\t8, 9, 10, 100, 101, 900, 901, 902, 903,\n"
	"\t\t200, 201, 202, 203, 204, 205, 206, 207,\n"
	"\t\t208, 209, 210, 211, 212, 213, 214, 910,\n"
	"\t\t911, 912, 913, 920, 921, 922, 923, 300,\n"
	"\t\t301, 302, 303, 304, 305, 306, 307, 308]\n"
	"\t},\n"
	"\t\"server\": {\n"
	"\t\t\"wii_id\": [100]\n"
	"\t}\n"
	"}\n"
	"\n";
#endif

#ifdef PLATFORM_PC
static const char* FROZEN_CONFIG_PC =
	"{\n"
	"\t\"paths\": {\n"
	"\t\t\"texturepack\": \"Cavex/assets\",\n"
	"\t\t\"worlds\": \"Cavex/saves\",\n"
	"\t\t\"bg\": \"Cavex/bg\",\n"
	"\t\t\"MP3\": \"Cavex/assets/sound\",\n"
	"\t\t\"sounds\": \"Cavex/assets/sound/sound\",\n"
	"\t\t\"tmp\": \"Cavex/tmp\",\n"
	"\t\t\"python_file\": \"Cavex/init.py\"\n"
	"\t},\n"
	"\t\"input\": {\n"
	"\t\t\"p1\": {\n"
	"    \"player_forward\": [84],      \n"
	"    \"player_backward\": [71],    \n"
	"    \"player_left\": [70],       \n"
	"    \"player_right\": [72],    \n"
	"\n"
	"    \"player_jump\": [89],        \n"
	"    \"player_sneak\": [78],\n"
	"\n"
	"    \"item_action_left\": [90],\n"
	"    \"item_action_right\": [85],  \n"
	"\n"
	"    \"scroll_left\": [90],       \n"
	"    \"scroll_right\": [88],        \n"
	"\n"
	"    \"inventory\": [67],          \n"
	"    \"open_menu\": [86],       \n"
	"\n"
	"    \"gui_up\": [84],\n"
	"    \"gui_down\": [71],\n"
	"    \"gui_left\": [70],\n"
	"    \"gui_right\": [72],\n"
	"\n"
	"    \"gui_click\": [90],\n"
	"    \"gui_click_alt\": [85],\n"
	"\n"
	"    \"screenshot\": [79],       \n"
	"    \"gui_back\": [86],\n"
	"\t\"any_button\": [71, 84, 72, 90, 85]\n"
	"},\n"
	"\"p2\": {\n"
	"\t\"player_forward\": [87],\n"
	"\t\t\"player_backward\": [83],\n"
	"\t\t\"player_left\": [65],\n"
	"\t\t\"player_right\": [68],\n"
	"\t\t\"player_jump\": [32],\n"
	"\t\t\"player_sneak\": [340],\n"
	"\t\t\"item_action_left\": [1000],\n"
	"\t\t\"item_action_right\": [1001],\n"
	"\t\t\"scroll_left\": [292],\n"
	"\t\t\"scroll_right\": [293],\n"
	"\t\t\"inventory\": [69],\n"
	"\t\t\"open_menu\": [256],\n"
	"\t\t\"gui_up\": [87, 265],\n"
	"\t\t\"gui_down\": [83, 264],\n"
	"\t\t\"gui_left\": [65, 263],\n"
	"\t\t\"gui_right\": [68, 262],\n"
	"\t\t\"gui_click\": [1000, 257],\n"
	"\t\t\"gui_click_alt\": [1001],\n"
	"\t\t\"screenshot\": [291],\n"
	"\t\t\"gui_back\": [256],\n"
	"\t\t\"any_button\": [87, 83, 65]\n"
	"},\n"
	"\t\n"
	"\t\t\"player_forward\": [87],\n"
	"\t\t\"player_backward\": [83],\n"
	"\t\t\"player_left\": [65],\n"
	"\t\t\"player_right\": [68],\n"
	"\t\t\"player_jump\": [32],\n"
	"\t\t\"player_sneak\": [340],\n"
	"\t\t\"item_action_left\": [1000],\n"
	"\t\t\"item_action_right\": [1001],\n"
	"\t\t\"scroll_left\": [292],\n"
	"\t\t\"scroll_right\": [293],\n"
	"\t\t\"inventory\": [69],\n"
	"\t\t\"open_menu\": [256],\n"
	"\t\t\"gui_up\": [87, 265],\n"
	"\t\t\"gui_down\": [83, 264],\n"
	"\t\t\"gui_left\": [65, 263],\n"
	"\t\t\"gui_right\": [68, 262],\n"
	"\t\t\"gui_click\": [1000, 257],\n"
	"\t\t\"gui_click_alt\": [1001],\n"
	"\t\t\"screenshot\": [291],\n"
	"\t\t\"gui_back\": [256],\n"
	"\t\t\"any_button\": [87, 83, 65]\n"
	"\t}\n"
	"}\n"
	"\n";
#endif

#endif
